Ver_2.0.0.8
CREATE TABLE T_Chat_Message (MTP VARCHAR(64),CHATINDEX VARCHAR(64),CONTENT VARCHAR(4000),MESSAGEID VARCHAR(64),SENDTIME VARCHAR(64),SENDUSERID VARCHAR(64),SESSIONID VARCHAR(64),TARGETID VARCHAR(64),SENDORRECEIVE VARCHAR(2),SENDSUCESSORFAIL int,flag varchar(2),READTIME VARCHAR(100),uploadOrDownPath VARCHAR(200),VOICEREAD VARCHAR(2),SPARE1 VARCHAR(100),SPARE2 VARCHAR(2), primary key(SESSIONID,CHATINDEX,MESSAGEID))
GO
CREATE TABLE T_Chat_Message_Group (MTP VARCHAR(64),CHATINDEX VARCHAR(64),CONTENT VARCHAR(4000),MESSAGEID VARCHAR(64),SENDTIME VARCHAR(64),SENDUSERID VARCHAR(64),SESSIONID VARCHAR(64),TARGETID VARCHAR(64),SENDORRECEIVE VARCHAR(2),SENDSUCESSORFAIL int,uploadOrDownPath VARCHAR(200),SPARE1 VARCHAR(100),VOICEREAD VARCHAR(2),SPARE2 VARCHAR(2),primary key(SESSIONID,CHATINDEX,MESSAGEID))
GO
CREATE TABLE T_Chat_Message_GroupBurn (MTP VARCHAR(64),CHATINDEX VARCHAR(64),CONTENT VARCHAR(4000),MESSAGEID VARCHAR(64),SENDTIME VARCHAR(64),SENDUSERID VARCHAR(64),SESSIONID VARCHAR(64),TARGETID VARCHAR(64),SENDORRECEIVE VARCHAR(2),SENDSUCESSORFAIL int,uploadOrDownPath VARCHAR(200),VOICEREAD VARCHAR(2),SPARE1 VARCHAR(100),SPARE2 VARCHAR(2),primary key(SESSIONID,CHATINDEX,MESSAGEID))
GO
CREATE TABLE T_Session (SESSIONID VARCHAR(64),USERID VARCHAR(64),GROUPID VARCHAR(64),UNREADCOUNT INT, LASTMSG VARCHAR(4000), LASTMSGTIMESTAMP  VARCHAR(64),LASTCHATINDEX VARCHAR(64),BURNUNREADCOUNT INT, BURNLASTMSG VARCHAR(4000), BURNLASTMSGTIMESTAMP  VARCHAR(64),BURNLASTCHATINDEX VARCHAR(64),ISBURNMODE int,TOPINDEX INT ,MESSAGEID VARCHAR(64), PRIMARY KEY(SESSIONID))
GO
CREATE TABLE T_MassMsg (MESSAGEID VARCHAR(64),SENDUSERID VARCHAR(64),TARGETID  VARCHAR(64), COMPANYCODE  VARCHAR(64), CONTENT VARCHAR(4000),SENDTIME VARCHAR(64),CHATINDEX VARCHAR(64), OS INT,SESSIONID VARCHAR(64),PRIMARY KEY(MESSAGEID))
GO
CREATE TABLE T_Version(VERSION VARCHAR(64),SENDTIME VARCHAR(64))
GO
CREATE TABLE C_USER_INFO (userId VARCHAR(32),LOGIN_NAME VARCHAR(16),PASSWORD VARCHAR(32),picture VARCHAR(128),userName VARCHAR(32),NICK VARCHAR(32),BIRTHDAY date,SEX int,MOBILE VARCHAR(16),TELEPHONE VARCHAR(32),departmentId varchar(32),COMPANY_CODE VARCHAR(32),position VARCHAR(32),EMAIL VARCHAR(64),REG_TIME datetime,UPDATE_TIME datetime,STATUS int,HOMETOWN VARCHAR(64),LOCATION VARCHAR(64),DEGREE VARCHAR(64),SCHOOL VARCHAR(64),STAR_SIGN VARCHAR(16),ANIMAL_SIGN VARCHAR(16),BLOOD_TYPE VARCHAR(128),signature VARCHAR(64),REMARK VARCHAR(64),QQ VARCHAR(16),accToken VARCHAR(32),accid VARCHAR(32),userNum VARCHAR(32),VOICE_MODE VARCHAR(8),VIBRATE_MODE VARCHAR(8),SPARE1 VARCHAR(100),SPARE2 VARCHAR(2), primary key(userId))
GO
CREATE TABLE C_DEPARTMENT (departmentId VARCHAR(32),departName VARCHAR(64),GRADE int,parentDepartId VARCHAR(32),COMPANY_CODE VARCHAR(32),STATUS CHAR(2),CREATE_USER_ID VARCHAR(32),CREATE_TIME datetime,UPDATE_USER_ID VARCHAR(32),UPDATE_TIME datetime,DESCRIPTION varchar(128),DEPARTMENT_SORT int, SPARE1 VARCHAR(100),SPARE2 VARCHAR(2),primary key(departmentId))
GO
CREATE TABLE C_Version(VERSION VARCHAR(64))
GO
