//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Antenna.Framework.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Antenna.Framework.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 未知错误 的本地化字符串。
        /// </summary>
        internal static string E_1001 {
            get {
                return ResourceManager.GetString("E_1001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数错误 的本地化字符串。
        /// </summary>
        internal static string E_1002 {
            get {
                return ResourceManager.GetString("E_1002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无效的版本号 的本地化字符串。
        /// </summary>
        internal static string E_1003 {
            get {
                return ResourceManager.GetString("E_1003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无效的token 的本地化字符串。
        /// </summary>
        internal static string E_1004 {
            get {
                return ResourceManager.GetString("E_1004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 json解析异常 的本地化字符串。
        /// </summary>
        internal static string E_1005 {
            get {
                return ResourceManager.GetString("E_1005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 终端类型错误 的本地化字符串。
        /// </summary>
        internal static string E_1006 {
            get {
                return ResourceManager.GetString("E_1006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户不存在 的本地化字符串。
        /// </summary>
        internal static string E_2001 {
            get {
                return ResourceManager.GetString("E_2001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名重复 的本地化字符串。
        /// </summary>
        internal static string E_2002 {
            get {
                return ResourceManager.GetString("E_2002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名密码不匹配 的本地化字符串。
        /// </summary>
        internal static string E_2003 {
            get {
                return ResourceManager.GetString("E_2003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 讨论组不存在 的本地化字符串。
        /// </summary>
        internal static string E_2004 {
            get {
                return ResourceManager.GetString("E_2004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 消息游标不存在 的本地化字符串。
        /// </summary>
        internal static string E_2005 {
            get {
                return ResourceManager.GetString("E_2005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 会话不存在 的本地化字符串。
        /// </summary>
        internal static string E_2006 {
            get {
                return ResourceManager.GetString("E_2006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 公司不存在 的本地化字符串。
        /// </summary>
        internal static string E_2007 {
            get {
                return ResourceManager.GetString("E_2007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新旧密码不一致 的本地化字符串。
        /// </summary>
        internal static string E_2008 {
            get {
                return ResourceManager.GetString("E_2008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户ID无效 的本地化字符串。
        /// </summary>
        internal static string E_2009 {
            get {
                return ResourceManager.GetString("E_2009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建讨论组的人必须在讨论组中 的本地化字符串。
        /// </summary>
        internal static string E_2010 {
            get {
                return ResourceManager.GetString("E_2010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退出讨论组错误，用户已经不在这个讨论组中 的本地化字符串。
        /// </summary>
        internal static string E_2011 {
            get {
                return ResourceManager.GetString("E_2011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 终端联系人信息版本号与服务器一直，不需要更新联系人信息 的本地化字符串。
        /// </summary>
        internal static string E_2012 {
            get {
                return ResourceManager.GetString("E_2012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Token 信息错误（不合法的token） 的本地化字符串。
        /// </summary>
        internal static string E_2013 {
            get {
                return ResourceManager.GetString("E_2013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户账号被停用 的本地化字符串。
        /// </summary>
        internal static string E_2014 {
            get {
                return ResourceManager.GetString("E_2014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有版本需要更新 的本地化字符串。
        /// </summary>
        internal static string E_3001 {
            get {
                return ResourceManager.GetString("E_3001", resourceCulture);
            }
        }
    }
}
