//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDK.AntSdk.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SDK.AntSdk.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 触角SDK添加意见反馈错误 的本地化字符串。
        /// </summary>
        internal static string AntSdkAddIdeaFeedBackError {
            get {
                return ResourceManager.GetString("AntSdkAddIdeaFeedBackError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 触角SDK配置信息的App版本信息不能为空 的本地化字符串。
        /// </summary>
        internal static string AntSdkAppVersionNotNull {
            get {
                return ResourceManager.GetString("AntSdkAppVersionNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 触角SDK修改用户密码错误 的本地化字符串。
        /// </summary>
        internal static string AntSdkChangePasswordError {
            get {
                return ResourceManager.GetString("AntSdkChangePasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 触角SDK切换用户状态错误 的本地化字符串。
        /// </summary>
        internal static string AntSdkChangeUserStateError {
            get {
                return ResourceManager.GetString("AntSdkChangeUserStateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 触角SDK检查更新错误 的本地化字符串。
        /// </summary>
        internal static string AntSdkCheckUpdateError {
            get {
                return ResourceManager.GetString("AntSdkCheckUpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 触角SDK登录客户系统错误 的本地化字符串。
        /// </summary>
        internal static string AntSdkCustomerLoginError {
            get {
                return ResourceManager.GetString("AntSdkCustomerLoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 触角SDK配置信息的客户系统HTTP地址不能为空 的本地化字符串。
        /// </summary>
        internal static string AntSdkCustomsHttpPrifxNotNull {
            get {
                return ResourceManager.GetString("AntSdkCustomsHttpPrifxNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据库错误 的本地化字符串。
        /// </summary>
        internal static string AntSdkE_10000 {
            get {
                return ResourceManager.GetString("AntSdkE_10000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未知错误 的本地化字符串。
        /// </summary>
        internal static string AntSdkE_10001 {
            get {
                return ResourceManager.GetString("AntSdkE_10001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数错误 的本地化字符串。
        /// </summary>
        internal static string AntSdkE_10002 {
            get {
                return ResourceManager.GetString("AntSdkE_10002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无效的版本号 的本地化字符串。
        /// </summary>
        internal static string AntSdkE_10003 {
            get {
                return ResourceManager.GetString("AntSdkE_10003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无效的token 的本地化字符串。
        /// </summary>
        internal static string AntSdkE_10004 {
            get {
                return ResourceManager.GetString("AntSdkE_10004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 json解析异常 的本地化字符串。
        /// </summary>
        internal static string AntSdkE_10005 {
            get {
                return ResourceManager.GetString("AntSdkE_10005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 终端类型错误 的本地化字符串。
        /// </summary>
        internal static string AntSdkE_10006 {
            get {
                return ResourceManager.GetString("AntSdkE_10006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统操作失败 的本地化字符串。
        /// </summary>
        internal static string AntSdkE_1001 {
            get {
                return ResourceManager.GetString("AntSdkE_1001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录名不能为空（用户名，手机，邮箱不能都为空） 的本地化字符串。
        /// </summary>
        internal static string AntSdkE_10010 {
            get {
                return ResourceManager.GetString("AntSdkE_10010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 手机号格式不合法 的本地化字符串。
        /// </summary>
        internal static string AntSdkE_10011 {
            get {
                return ResourceManager.GetString("AntSdkE_10011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 邮箱格式不合法 的本地化字符串。
        /// </summary>
        internal static string AntSdkE_10012 {
            get {
                return ResourceManager.GetString("AntSdkE_10012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码格式不合法 的本地化字符串。
        /// </summary>
        internal static string AntSdkE_10013 {
            get {
                return ResourceManager.GetString("AntSdkE_10013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名密码不匹配 的本地化字符串。
        /// </summary>
        internal static string AntSdkE_10014 {
            get {
                return ResourceManager.GetString("AntSdkE_10014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该账号已被禁用 的本地化字符串。
        /// </summary>
        internal static string AntSdkE_10015 {
            get {
                return ResourceManager.GetString("AntSdkE_10015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该用户名已存在 的本地化字符串。
        /// </summary>
        internal static string AntSdkE_10016 {
            get {
                return ResourceManager.GetString("AntSdkE_10016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该手机号已存在 的本地化字符串。
        /// </summary>
        internal static string AntSdkE_10017 {
            get {
                return ResourceManager.GetString("AntSdkE_10017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该邮箱已存在 的本地化字符串。
        /// </summary>
        internal static string AntSdkE_10018 {
            get {
                return ResourceManager.GetString("AntSdkE_10018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新密码不能与旧密码一致 的本地化字符串。
        /// </summary>
        internal static string AntSdkE_10019 {
            get {
                return ResourceManager.GetString("AntSdkE_10019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数错误 的本地化字符串。
        /// </summary>
        internal static string AntSdkE_1002 {
            get {
                return ResourceManager.GetString("AntSdkE_1002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该用户不存在 的本地化字符串。
        /// </summary>
        internal static string AntSdkE_10020 {
            get {
                return ResourceManager.GetString("AntSdkE_10020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 旧密码有误 的本地化字符串。
        /// </summary>
        internal static string AntSdkE_10021 {
            get {
                return ResourceManager.GetString("AntSdkE_10021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户不存在 的本地化字符串。
        /// </summary>
        internal static string AntSdkE_20001 {
            get {
                return ResourceManager.GetString("AntSdkE_20001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名重复 的本地化字符串。
        /// </summary>
        internal static string AntSdkE_20002 {
            get {
                return ResourceManager.GetString("AntSdkE_20002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名密码不匹配 的本地化字符串。
        /// </summary>
        internal static string AntSdkE_20003 {
            get {
                return ResourceManager.GetString("AntSdkE_20003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 讨论组不存在 的本地化字符串。
        /// </summary>
        internal static string AntSdkE_20004 {
            get {
                return ResourceManager.GetString("AntSdkE_20004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 消息游标不存在 的本地化字符串。
        /// </summary>
        internal static string AntSdkE_20005 {
            get {
                return ResourceManager.GetString("AntSdkE_20005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 会话不存在 的本地化字符串。
        /// </summary>
        internal static string AntSdkE_20006 {
            get {
                return ResourceManager.GetString("AntSdkE_20006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 公司不存在 的本地化字符串。
        /// </summary>
        internal static string AntSdkE_20007 {
            get {
                return ResourceManager.GetString("AntSdkE_20007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新旧密码不一致 的本地化字符串。
        /// </summary>
        internal static string AntSdkE_20008 {
            get {
                return ResourceManager.GetString("AntSdkE_20008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无效的用户 的本地化字符串。
        /// </summary>
        internal static string AntSdkE_20009 {
            get {
                return ResourceManager.GetString("AntSdkE_20009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建讨论组的人必须在讨论组中 的本地化字符串。
        /// </summary>
        internal static string AntSdkE_20010 {
            get {
                return ResourceManager.GetString("AntSdkE_20010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退出讨论组错误，用户已经不在这个讨论组中 的本地化字符串。
        /// </summary>
        internal static string AntSdkE_20011 {
            get {
                return ResourceManager.GetString("AntSdkE_20011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 终端联系人信息版本号与服务器一致，不需要更新联系人信息 的本地化字符串。
        /// </summary>
        internal static string AntSdkE_20012 {
            get {
                return ResourceManager.GetString("AntSdkE_20012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户账号被停用 的本地化字符串。
        /// </summary>
        internal static string AntSdkE_20013 {
            get {
                return ResourceManager.GetString("AntSdkE_20013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名或密码错误 的本地化字符串。
        /// </summary>
        internal static string AntSdkE_2003 {
            get {
                return ResourceManager.GetString("AntSdkE_2003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新密码不能与旧密码一致 的本地化字符串。
        /// </summary>
        internal static string AntSdkE_2008 {
            get {
                return ResourceManager.GetString("AntSdkE_2008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该用户不存在 的本地化字符串。
        /// </summary>
        internal static string AntSdkE_2013 {
            get {
                return ResourceManager.GetString("AntSdkE_2013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有版本需要更新 的本地化字符串。
        /// </summary>
        internal static string AntSdkE_30001 {
            get {
                return ResourceManager.GetString("AntSdkE_30001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除讨论组错误，不是管理员不能删除讨论组 的本地化字符串。
        /// </summary>
        internal static string AntSdkE_40001 {
            get {
                return ResourceManager.GetString("AntSdkE_40001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连接redis服务器异常 的本地化字符串。
        /// </summary>
        internal static string AntSdkE_91101 {
            get {
                return ResourceManager.GetString("AntSdkE_91101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作redis服务器异常 的本地化字符串。
        /// </summary>
        internal static string AntSdkE_91102 {
            get {
                return ResourceManager.GetString("AntSdkE_91102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数异常 的本地化字符串。
        /// </summary>
        internal static string AntSdkE_91103 {
            get {
                return ResourceManager.GetString("AntSdkE_91103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作redis错误 的本地化字符串。
        /// </summary>
        internal static string AntSdkE_91104 {
            get {
                return ResourceManager.GetString("AntSdkE_91104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 触角SDK获取增量联系人信息错误 的本地化字符串。
        /// </summary>
        internal static string AntSdkGetAddContactsError {
            get {
                return ResourceManager.GetString("AntSdkGetAddContactsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 触角SDK获取联系人信息错误 的本地化字符串。
        /// </summary>
        internal static string AntSdkGetContactInfoError {
            get {
                return ResourceManager.GetString("AntSdkGetContactInfoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 触角SDK获取部门下说有用户的状态错误 的本地化字符串。
        /// </summary>
        internal static string AntSdkGetDepartUserStateError {
            get {
                return ResourceManager.GetString("AntSdkGetDepartUserStateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 触角SDK获取意见反馈类型错误 的本地化字符串。
        /// </summary>
        internal static string AntSdkGetUserIdeaTypeError {
            get {
                return ResourceManager.GetString("AntSdkGetUserIdeaTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 触角SDK获取用户信息错误 的本地化字符串。
        /// </summary>
        internal static string AntSdkGetUserInfoError {
            get {
                return ResourceManager.GetString("AntSdkGetUserInfoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 触角SDK获取用户回复用语设置错误 的本地化字符串。
        /// </summary>
        internal static string AntSdkGetUserReturnSettingError {
            get {
                return ResourceManager.GetString("AntSdkGetUserReturnSettingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 触角SDK转换Http请求返回的基础结构信息出错 的本地化字符串。
        /// </summary>
        internal static string AntSdkHttpCommonBaseSchemaError {
            get {
                return ResourceManager.GetString("AntSdkHttpCommonBaseSchemaError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 触角SDK转换Http请求返回的基础结构内容信息为空 的本地化字符串。
        /// </summary>
        internal static string AntSdkHttpCommonBaseSchemaNull {
            get {
                return ResourceManager.GetString("AntSdkHttpCommonBaseSchemaNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 触角SDK转换Http请求返回的基础结构内容错误 的本地化字符串。
        /// </summary>
        internal static string AntSdkHttpCommonOutSchemaError {
            get {
                return ResourceManager.GetString("AntSdkHttpCommonOutSchemaError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请求失败，请联系系统管理员 的本地化字符串。
        /// </summary>
        internal static string AntSdkHttpRequestFail {
            get {
                return ResourceManager.GetString("AntSdkHttpRequestFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 触角SDK的Http请求没有返回任何信息 的本地化字符串。
        /// </summary>
        internal static string AntSdkHttpResponseNull {
            get {
                return ResourceManager.GetString("AntSdkHttpResponseNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 触角SDK退出登录错误 的本地化字符串。
        /// </summary>
        internal static string AntSdkLoginOutError {
            get {
                return ResourceManager.GetString("AntSdkLoginOutError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 触角SDK未启动 的本地化字符串。
        /// </summary>
        internal static string AntSdkNotStart {
            get {
                return ResourceManager.GetString("AntSdkNotStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 触角SDK发送自定义消息，消息类型错误 的本地化字符串。
        /// </summary>
        internal static string AntSdkSendCtomMsgTypeError {
            get {
                return ResourceManager.GetString("AntSdkSendCtomMsgTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 触角SDK配置信息的触角服务HTTP地址不能为空 的本地化字符串。
        /// </summary>
        internal static string AntSdkServiceHttpPrifxNotNull {
            get {
                return ResourceManager.GetString("AntSdkServiceHttpPrifxNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 触角SDK 登录触角服务时返回的用户ID为空 的本地化字符串。
        /// </summary>
        internal static string AntSdkServiceLoginReturnError {
            get {
                return ResourceManager.GetString("AntSdkServiceLoginReturnError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 触角SDK启动产品ID不能为空 的本地化字符串。
        /// </summary>
        internal static string AntSdkStartAppKeyNotNull {
            get {
                return ResourceManager.GetString("AntSdkStartAppKeyNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 触角SDK启动产品密钥不能为空 的本地化字符串。
        /// </summary>
        internal static string AntSdkStartAppSecretNotNull {
            get {
                return ResourceManager.GetString("AntSdkStartAppSecretNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 触角SDK启动公司代码不能为空 的本地化字符串。
        /// </summary>
        internal static string AntSdkStartCompanyCodeNotNull {
            get {
                return ResourceManager.GetString("AntSdkStartCompanyCodeNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 触角SDK启动文件上传地址不能为空 的本地化字符串。
        /// </summary>
        internal static string AntSdkStartFileUploadNotNull {
            get {
                return ResourceManager.GetString("AntSdkStartFileUploadNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 触角SDK启动企业级服务HTTP地址不能为空 的本地化字符串。
        /// </summary>
        internal static string AntSdkStartHttpPrefStuffNotNull {
            get {
                return ResourceManager.GetString("AntSdkStartHttpPrefStuffNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 触角SDK创建讨论组进行订阅讨论组主题时错误 的本地化字符串。
        /// </summary>
        internal static string AntSdkSubscribeCreateGroupTopicsError {
            get {
                return ResourceManager.GetString("AntSdkSubscribeCreateGroupTopicsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 触角SDK删除组成员包含自己进行取消订阅讨论组主题时错误 的本地化字符串。
        /// </summary>
        internal static string AntSdkSubscribeDeleteGroupMemberTopicsError {
            get {
                return ResourceManager.GetString("AntSdkSubscribeDeleteGroupMemberTopicsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 触角SDK解散讨论组进行取消订阅讨论组主题时错误 的本地化字符串。
        /// </summary>
        internal static string AntSdkSubscribeDissolveGroupTopicsError {
            get {
                return ResourceManager.GetString("AntSdkSubscribeDissolveGroupTopicsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 触角SDK退出讨论组进行取消订阅讨论组主题时错误 的本地化字符串。
        /// </summary>
        internal static string AntSdkSubscribeExitGroupTopicsError {
            get {
                return ResourceManager.GetString("AntSdkSubscribeExitGroupTopicsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 触角SDK获取用户讨论组进行订阅讨论组主题时错误 的本地化字符串。
        /// </summary>
        internal static string AntSdkSubscribeGroupTopicsError {
            get {
                return ResourceManager.GetString("AntSdkSubscribeGroupTopicsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 触角SDK个性化设置接收消息订阅讨论组主题时错误 的本地化字符串。
        /// </summary>
        internal static string AntSdkSubscribePersonalAcceptTopicsError {
            get {
                return ResourceManager.GetString("AntSdkSubscribePersonalAcceptTopicsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 触角SDK个性化设置屏蔽消息取消订阅讨论组主题时错误 的本地化字符串。
        /// </summary>
        internal static string AntSdkSubscribePersonalBlockTopicsError {
            get {
                return ResourceManager.GetString("AntSdkSubscribePersonalBlockTopicsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请求超时 的本地化字符串。
        /// </summary>
        internal static string SdkHttpRequestTimeOut {
            get {
                return ResourceManager.GetString("SdkHttpRequestTimeOut", resourceCulture);
            }
        }
    }
}
