//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDK.Service.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SDK.Service.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 服务器异常 的本地化字符串。
        /// </summary>
        internal static string E_00000 {
            get {
                return ResourceManager.GetString("E_00000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户认证失败 的本地化字符串。
        /// </summary>
        internal static string E_00007 {
            get {
                return ResourceManager.GetString("E_00007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数错误 的本地化字符串。
        /// </summary>
        internal static string E_1002 {
            get {
                return ResourceManager.GetString("E_1002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无效的token 的本地化字符串。
        /// </summary>
        internal static string E_1004 {
            get {
                return ResourceManager.GetString("E_1004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据操作失败 的本地化字符串。
        /// </summary>
        internal static string E_1008 {
            get {
                return ResourceManager.GetString("E_1008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 讨论组ID不存在 的本地化字符串。
        /// </summary>
        internal static string E_2004 {
            get {
                return ResourceManager.GetString("E_2004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建讨论组的人必须在讨论组中 的本地化字符串。
        /// </summary>
        internal static string E_2010 {
            get {
                return ResourceManager.GetString("E_2010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户已经不在这个讨论组中 的本地化字符串。
        /// </summary>
        internal static string E_2011 {
            get {
                return ResourceManager.GetString("E_2011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户不是讨论组的管理员 的本地化字符串。
        /// </summary>
        internal static string E_2014 {
            get {
                return ResourceManager.GetString("E_2014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 讨论组公告id不存在 的本地化字符串。
        /// </summary>
        internal static string E_2015 {
            get {
                return ResourceManager.GetString("E_2015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 找不到成员信息 的本地化字符串。
        /// </summary>
        internal static string E_5001 {
            get {
                return ResourceManager.GetString("E_5001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 找不到聊天室信息 的本地化字符串。
        /// </summary>
        internal static string E_5002 {
            get {
                return ResourceManager.GetString("E_5002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当次操作沒有成员 的本地化字符串。
        /// </summary>
        internal static string E_5003 {
            get {
                return ResourceManager.GetString("E_5003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当次操作成员数过多 的本地化字符串。
        /// </summary>
        internal static string E_5004 {
            get {
                return ResourceManager.GetString("E_5004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建聊天室失败 的本地化字符串。
        /// </summary>
        internal static string E_5005 {
            get {
                return ResourceManager.GetString("E_5005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除聊天室失败 的本地化字符串。
        /// </summary>
        internal static string E_5006 {
            get {
                return ResourceManager.GetString("E_5006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加聊天室成员失败 的本地化字符串。
        /// </summary>
        internal static string E_5007 {
            get {
                return ResourceManager.GetString("E_5007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除聊天室成员失败 的本地化字符串。
        /// </summary>
        internal static string E_5008 {
            get {
                return ResourceManager.GetString("E_5008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 改变成员属性失败 的本地化字符串。
        /// </summary>
        internal static string E_5009 {
            get {
                return ResourceManager.GetString("E_5009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改聊天室信息失败 的本地化字符串。
        /// </summary>
        internal static string E_5010 {
            get {
                return ResourceManager.GetString("E_5010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退出聊天室失败 的本地化字符串。
        /// </summary>
        internal static string E_5011 {
            get {
                return ResourceManager.GetString("E_5011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该成员已在聊天室，邀请失败 的本地化字符串。
        /// </summary>
        internal static string E_5012 {
            get {
                return ResourceManager.GetString("E_5012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 邀请重复，等候处理 的本地化字符串。
        /// </summary>
        internal static string E_5013 {
            get {
                return ResourceManager.GetString("E_5013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注册公司失败 的本地化字符串。
        /// </summary>
        internal static string E_5101 {
            get {
                return ResourceManager.GetString("E_5101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该公司不存在 的本地化字符串。
        /// </summary>
        internal static string E_5102 {
            get {
                return ResourceManager.GetString("E_5102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注册应用失败 的本地化字符串。
        /// </summary>
        internal static string E_5103 {
            get {
                return ResourceManager.GetString("E_5103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该应用不存在 的本地化字符串。
        /// </summary>
        internal static string E_5104 {
            get {
                return ResourceManager.GetString("E_5104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统错误，找不到缓存中的对象 的本地化字符串。
        /// </summary>
        internal static string E_90000 {
            get {
                return ResourceManager.GetString("E_90000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户退出异常 的本地化字符串。
        /// </summary>
        internal static string E_90103 {
            get {
                return ResourceManager.GetString("E_90103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改密码异常 的本地化字符串。
        /// </summary>
        internal static string E_90104 {
            get {
                return ResourceManager.GetString("E_90104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 切换状态异常 的本地化字符串。
        /// </summary>
        internal static string E_90105 {
            get {
                return ResourceManager.GetString("E_90105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询公司客服异常 的本地化字符串。
        /// </summary>
        internal static string E_90118 {
            get {
                return ResourceManager.GetString("E_90118", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户登录异常 的本地化字符串。
        /// </summary>
        internal static string E_90119 {
            get {
                return ResourceManager.GetString("E_90119", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户被禁用 的本地化字符串。
        /// </summary>
        internal static string E_90125 {
            get {
                return ResourceManager.GetString("E_90125", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 优先受理会话异常 的本地化字符串。
        /// </summary>
        internal static string E_90205 {
            get {
                return ResourceManager.GetString("E_90205", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询访客历史异常 的本地化字符串。
        /// </summary>
        internal static string E_90206 {
            get {
                return ResourceManager.GetString("E_90206", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 直接会话异常 的本地化字符串。
        /// </summary>
        internal static string E_90207 {
            get {
                return ResourceManager.GetString("E_90207", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 邀请会话异常 的本地化字符串。
        /// </summary>
        internal static string E_90208 {
            get {
                return ResourceManager.GetString("E_90208", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询公司标签异常 的本地化字符串。
        /// </summary>
        internal static string E_90210 {
            get {
                return ResourceManager.GetString("E_90210", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结束会话异常 的本地化字符串。
        /// </summary>
        internal static string E_90310 {
            get {
                return ResourceManager.GetString("E_90310", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载会话内容异常 的本地化字符串。
        /// </summary>
        internal static string E_90311 {
            get {
                return ResourceManager.GetString("E_90311", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载会话历史异常 的本地化字符串。
        /// </summary>
        internal static string E_90312 {
            get {
                return ResourceManager.GetString("E_90312", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 访客已经结束咨询 的本地化字符串。
        /// </summary>
        internal static string E_90323 {
            get {
                return ResourceManager.GetString("E_90323", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 访客已经结束咨询 的本地化字符串。
        /// </summary>
        internal static string E_90325 {
            get {
                return ResourceManager.GetString("E_90325", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发起转接请求异常 的本地化字符串。
        /// </summary>
        internal static string E_90332 {
            get {
                return ResourceManager.GetString("E_90332", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发送确认转接异常 的本地化字符串。
        /// </summary>
        internal static string E_90333 {
            get {
                return ResourceManager.GetString("E_90333", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询公共常用语异常 的本地化字符串。
        /// </summary>
        internal static string E_90403 {
            get {
                return ResourceManager.GetString("E_90403", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询个人常用语异常 的本地化字符串。
        /// </summary>
        internal static string E_90405 {
            get {
                return ResourceManager.GetString("E_90405", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询个人常用语目录异常 的本地化字符串。
        /// </summary>
        internal static string E_90406 {
            get {
                return ResourceManager.GetString("E_90406", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加个人常用语异常 的本地化字符串。
        /// </summary>
        internal static string E_90407 {
            get {
                return ResourceManager.GetString("E_90407", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除个人常用语异常 的本地化字符串。
        /// </summary>
        internal static string E_90408 {
            get {
                return ResourceManager.GetString("E_90408", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改个人常用语异常 的本地化字符串。
        /// </summary>
        internal static string E_90409 {
            get {
                return ResourceManager.GetString("E_90409", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 公司代码不存在 的本地化字符串。
        /// </summary>
        internal static string E_90606 {
            get {
                return ResourceManager.GetString("E_90606", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 公司已禁用 的本地化字符串。
        /// </summary>
        internal static string E_90607 {
            get {
                return ResourceManager.GetString("E_90607", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服务已过期 的本地化字符串。
        /// </summary>
        internal static string E_90608 {
            get {
                return ResourceManager.GetString("E_90608", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名或密码错误 的本地化字符串。
        /// </summary>
        internal static string E_90609 {
            get {
                return ResourceManager.GetString("E_90609", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客服坐席已满 的本地化字符串。
        /// </summary>
        internal static string E_90610 {
            get {
                return ResourceManager.GetString("E_90610", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取未评估会话异常 的本地化字符串。
        /// </summary>
        internal static string E_90701 {
            get {
                return ResourceManager.GetString("E_90701", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 评估会话异常 的本地化字符串。
        /// </summary>
        internal static string E_90702 {
            get {
                return ResourceManager.GetString("E_90702", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询公司主题异常 的本地化字符串。
        /// </summary>
        internal static string E_90801 {
            get {
                return ResourceManager.GetString("E_90801", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加知识库问题异常 的本地化字符串。
        /// </summary>
        internal static string E_91201 {
            get {
                return ResourceManager.GetString("E_91201", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询知识库答案异常 的本地化字符串。
        /// </summary>
        internal static string E_91202 {
            get {
                return ResourceManager.GetString("E_91202", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 知识库问题已存在 的本地化字符串。
        /// </summary>
        internal static string E_91203 {
            get {
                return ResourceManager.GetString("E_91203", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询常用链接异常 的本地化字符串。
        /// </summary>
        internal static string E_91501 {
            get {
                return ResourceManager.GetString("E_91501", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询常用文件异常 的本地化字符串。
        /// </summary>
        internal static string E_91502 {
            get {
                return ResourceManager.GetString("E_91502", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SDK添加用户黑名单错误 的本地化字符串。
        /// </summary>
        internal static string SdkAddBlacklistError {
            get {
                return ResourceManager.GetString("SdkAddBlacklistError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SDK添加聊天室成员失败 的本地化字符串。
        /// </summary>
        internal static string SdkAddChartRommMemberError {
            get {
                return ResourceManager.GetString("SdkAddChartRommMemberError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SD添加聊天室成员错误 的本地化字符串。
        /// </summary>
        internal static string SdkAddChatRoomMembersError {
            get {
                return ResourceManager.GetString("SdkAddChatRoomMembersError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SDK添加群公告错误 的本地化字符串。
        /// </summary>
        internal static string SdkAddNotificationsError {
            get {
                return ResourceManager.GetString("SdkAddNotificationsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SDK手机端切换运行状态错误 的本地化字符串。
        /// </summary>
        internal static string SdkChangeAppStatusError {
            get {
                return ResourceManager.GetString("SdkChangeAppStatusError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SDK连接消息服务失败 的本地化字符串。
        /// </summary>
        internal static string SdkConectServiceFail {
            get {
                return ResourceManager.GetString("SdkConectServiceFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SDK创建聊天室错误 的本地化字符串。
        /// </summary>
        internal static string SdkCreateChatRoomError {
            get {
                return ResourceManager.GetString("SdkCreateChatRoomError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SDK创建讨论组错误 的本地化字符串。
        /// </summary>
        internal static string SdkCreateGroupError {
            get {
                return ResourceManager.GetString("SdkCreateGroupError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SDK移除用户黑名单错误 的本地化字符串。
        /// </summary>
        internal static string SdkDelBlacklistError {
            get {
                return ResourceManager.GetString("SdkDelBlacklistError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SDK删除聊天室成员错误 的本地化字符串。
        /// </summary>
        internal static string SdkDelChartRommMemberError {
            get {
                return ResourceManager.GetString("SdkDelChartRommMemberError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SDK删除聊天室错误 的本地化字符串。
        /// </summary>
        internal static string SdkDeleteChatRoomError {
            get {
                return ResourceManager.GetString("SdkDeleteChatRoomError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SDK删除群公告错误 的本地化字符串。
        /// </summary>
        internal static string SdkDeleteNotificationsByIdError {
            get {
                return ResourceManager.GetString("SdkDeleteNotificationsByIdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SDK解散讨论组错误 的本地化字符串。
        /// </summary>
        internal static string SdkDissolveGroupError {
            get {
                return ResourceManager.GetString("SdkDissolveGroupError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SDK成员退出聊天室失败 的本地化字符串。
        /// </summary>
        internal static string SdkExtChartRommFail {
            get {
                return ResourceManager.GetString("SdkExtChartRommFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SDK查询黑名单ID列表错误 的本地化字符串。
        /// </summary>
        internal static string SdkFindBlacklistsError {
            get {
                return ResourceManager.GetString("SdkFindBlacklistsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SDK获取群的所有公告错误 的本地化字符串。
        /// </summary>
        internal static string SdkGetGroupNotificationsError {
            get {
                return ResourceManager.GetString("SdkGetGroupNotificationsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SDK获取消息服务器配置失败 的本地化字符串。
        /// </summary>
        internal static string SdkGetMqttConfigFail {
            get {
                return ResourceManager.GetString("SdkGetMqttConfigFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SDK通过ID获取群公告错误 的本地化字符串。
        /// </summary>
        internal static string SdkGetNotificationsByIdError {
            get {
                return ResourceManager.GetString("SdkGetNotificationsByIdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SDK获取用户的讨论组错误 的本地化字符串。
        /// </summary>
        internal static string SdkGetUserGroupError {
            get {
                return ResourceManager.GetString("SdkGetUserGroupError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SDK退出讨论组错误 的本地化字符串。
        /// </summary>
        internal static string SdkGroupExitError {
            get {
                return ResourceManager.GetString("SdkGroupExitError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SDK群主转让错误 的本地化字符串。
        /// </summary>
        internal static string SdkGroupOwnerChangeError {
            get {
                return ResourceManager.GetString("SdkGroupOwnerChangeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SDK获取讨论组成员信息错误 的本地化字符串。
        /// </summary>
        internal static string SdkGroupUserInfoError {
            get {
                return ResourceManager.GetString("SdkGroupUserInfoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SDK处理邀请错误 的本地化字符串。
        /// </summary>
        internal static string SdkHandleInviteRommError {
            get {
                return ResourceManager.GetString("SdkHandleInviteRommError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SDK转换Http请求返回的基础结构信息出错 的本地化字符串。
        /// </summary>
        internal static string SdkHttpCommonBaseSchemaError {
            get {
                return ResourceManager.GetString("SdkHttpCommonBaseSchemaError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SDK转换Http请求返回的基础结构内容信息为空 的本地化字符串。
        /// </summary>
        internal static string SdkHttpCommonBaseSchemaNull {
            get {
                return ResourceManager.GetString("SdkHttpCommonBaseSchemaNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SDK转换Http请求返回的基础结构内容错误 的本地化字符串。
        /// </summary>
        internal static string SdkHttpCommonOutSchemaError {
            get {
                return ResourceManager.GetString("SdkHttpCommonOutSchemaError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请求失败，请联系系统管理员 的本地化字符串。
        /// </summary>
        internal static string SdkHttpRequestFail {
            get {
                return ResourceManager.GetString("SdkHttpRequestFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请求超时 的本地化字符串。
        /// </summary>
        internal static string SdkHttpRequestTimeOut {
            get {
                return ResourceManager.GetString("SdkHttpRequestTimeOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SDK的Http请求没有返回任何信息 的本地化字符串。
        /// </summary>
        internal static string SdkHttpResponseNull {
            get {
                return ResourceManager.GetString("SdkHttpResponseNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上传的文件不存在，请重新选择正确的文件上传 的本地化字符串。
        /// </summary>
        internal static string SdkHttpUploadFileNoExist {
            get {
                return ResourceManager.GetString("SdkHttpUploadFileNoExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SDK邀请加入聊天室错误 的本地化字符串。
        /// </summary>
        internal static string SdkInviteJoinRommError {
            get {
                return ResourceManager.GetString("SdkInviteJoinRommError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SDK登录服务器失败 的本地化字符串。
        /// </summary>
        internal static string SdkLoginServiceFail {
            get {
                return ResourceManager.GetString("SdkLoginServiceFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SDK消息服务器连接异常 的本地化字符串。
        /// </summary>
        internal static string SdkMqServiceException {
            get {
                return ResourceManager.GetString("SdkMqServiceException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MQTT连接失败 的本地化字符串。
        /// </summary>
        internal static string SdkMqttConnectFail {
            get {
                return ResourceManager.GetString("SdkMqttConnectFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MQTT连接成功 的本地化字符串。
        /// </summary>
        internal static string SdkMqttConnectSuccess {
            get {
                return ResourceManager.GetString("SdkMqttConnectSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MQTT断开连接失败 的本地化字符串。
        /// </summary>
        internal static string SdkMqttDisconnectFail {
            get {
                return ResourceManager.GetString("SdkMqttDisconnectFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MQTT断开连接 的本地化字符串。
        /// </summary>
        internal static string SdkMqttDisconnectSuccess {
            get {
                return ResourceManager.GetString("SdkMqttDisconnectSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SDK发布MQTT消息失败 的本地化字符串。
        /// </summary>
        internal static string SdkMsPublishFail {
            get {
                return ResourceManager.GetString("SdkMsPublishFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SDK发布MQTT消息成功 的本地化字符串。
        /// </summary>
        internal static string SdkMsPublishSuccess {
            get {
                return ResourceManager.GetString("SdkMsPublishSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SDK未启动 的本地化字符串。
        /// </summary>
        internal static string SdkNotStart {
            get {
                return ResourceManager.GetString("SdkNotStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SDK查询app下的所有聊天室错误 的本地化字符串。
        /// </summary>
        internal static string SdkQryAllRommInfoError {
            get {
                return ResourceManager.GetString("SdkQryAllRommInfoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SDK查询用户所在聊天室错误 的本地化字符串。
        /// </summary>
        internal static string SdkQryInAllRommError {
            get {
                return ResourceManager.GetString("SdkQryInAllRommError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SDK查询用户所在聊天室错误 的本地化字符串。
        /// </summary>
        internal static string SdkQryInChartRommError {
            get {
                return ResourceManager.GetString("SdkQryInChartRommError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SDK查询离线消息错误 的本地化字符串。
        /// </summary>
        internal static string SdkQryOffLineInfoError {
            get {
                return ResourceManager.GetString("SdkQryOffLineInfoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SDK查询聊天室所有成员基本信息错误 的本地化字符串。
        /// </summary>
        internal static string SdkQryRommMembersInfoError {
            get {
                return ResourceManager.GetString("SdkQryRommMembersInfoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SDK查询聊天室单个成员详细信息错误 的本地化字符串。
        /// </summary>
        internal static string SdkQryRommSingleMembersInfoError {
            get {
                return ResourceManager.GetString("SdkQryRommSingleMembersInfoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SDK查询单个聊天室详细信息错误 的本地化字符串。
        /// </summary>
        internal static string SdkQrySingleRommError {
            get {
                return ResourceManager.GetString("SdkQrySingleRommError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SDK解析聊天@消息错误 的本地化字符串。
        /// </summary>
        internal static string SdkReceiveChatMsgAtError {
            get {
                return ResourceManager.GetString("SdkReceiveChatMsgAtError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SDK解析聊天音频消息错误 的本地化字符串。
        /// </summary>
        internal static string SdkReceiveChatMsgAudioError {
            get {
                return ResourceManager.GetString("SdkReceiveChatMsgAudioError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SDK解析聊天消息错误 的本地化字符串。
        /// </summary>
        internal static string SdkReceiveChatMsgError {
            get {
                return ResourceManager.GetString("SdkReceiveChatMsgError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SDK解析聊天文件消息错误 的本地化字符串。
        /// </summary>
        internal static string SdkReceiveChatMsgFileError {
            get {
                return ResourceManager.GetString("SdkReceiveChatMsgFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SDK解析聊天地理位置消息错误 的本地化字符串。
        /// </summary>
        internal static string SdkReceiveChatMsgMapLocationError {
            get {
                return ResourceManager.GetString("SdkReceiveChatMsgMapLocationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SDK解析聊天图文混合消息错误 的本地化字符串。
        /// </summary>
        internal static string SdkReceiveChatMsgMixImageTextError {
            get {
                return ResourceManager.GetString("SdkReceiveChatMsgMixImageTextError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SDK解析聊天多人视频消息错误 的本地化字符串。
        /// </summary>
        internal static string SdkReceiveChatMsgMultiAudioVideoError {
            get {
                return ResourceManager.GetString("SdkReceiveChatMsgMultiAudioVideoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SDK解析聊天图片消息错误 的本地化字符串。
        /// </summary>
        internal static string SdkReceiveChatMsgPictureError {
            get {
                return ResourceManager.GetString("SdkReceiveChatMsgPictureError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SDK解析聊天视频消息错误 的本地化字符串。
        /// </summary>
        internal static string SdkReceiveChatMsgVideoError {
            get {
                return ResourceManager.GetString("SdkReceiveChatMsgVideoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SDK收到MQTT消息 的本地化字符串。
        /// </summary>
        internal static string SdkReceivedMqttMessage {
            get {
                return ResourceManager.GetString("SdkReceivedMqttMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SDK消息漫游错误 的本地化字符串。
        /// </summary>
        internal static string SdkRoamMessageError {
            get {
                return ResourceManager.GetString("SdkRoamMessageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SDK获取发送心跳信息的数据的Json数据错误 的本地化字符串。
        /// </summary>
        internal static string SdkSedGetHeartbeatJsonstrError {
            get {
                return ResourceManager.GetString("SdkSedGetHeartbeatJsonstrError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 撤销消息时消息ID不能空 的本地化字符串。
        /// </summary>
        internal static string SdkSendChatMsgRevocationMsIdError {
            get {
                return ResourceManager.GetString("SdkSendChatMsgRevocationMsIdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发送的聊天消息不符合SDK聊天消息数据结构 的本地化字符串。
        /// </summary>
        internal static string SdkSendChatMsgTypeError {
            get {
                return ResourceManager.GetString("SdkSendChatMsgTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发送的终端消息不符合SDK终端消息数据结构 的本地化字符串。
        /// </summary>
        internal static string SdkSendTerminalMsgTypeError {
            get {
                return ResourceManager.GetString("SdkSendTerminalMsgTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SDK设置聊天室的接收消息类型错误 的本地化字符串。
        /// </summary>
        internal static string SdkSetRommMsgTypeError {
            get {
                return ResourceManager.GetString("SdkSetRommMsgTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SDK设置用户的接收消息类型错误 的本地化字符串。
        /// </summary>
        internal static string SdkSetUserMsgTypeError {
            get {
                return ResourceManager.GetString("SdkSetUserMsgTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SDK启动产品ID不能为空 的本地化字符串。
        /// </summary>
        internal static string SdkStartAppKeyNotNull {
            get {
                return ResourceManager.GetString("SdkStartAppKeyNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SDK启动产品密钥不能为空 的本地化字符串。
        /// </summary>
        internal static string SdkStartAppSecretNotNull {
            get {
                return ResourceManager.GetString("SdkStartAppSecretNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SDK启动公司代码不能为空 的本地化字符串。
        /// </summary>
        internal static string SdkStartCompanyCodeNotNull {
            get {
                return ResourceManager.GetString("SdkStartCompanyCodeNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SDK启动文件上传地址不能为空 的本地化字符串。
        /// </summary>
        internal static string SdkStartFileUploadNotNull {
            get {
                return ResourceManager.GetString("SdkStartFileUploadNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SDK启动企业级服务HTTP地址不能为空 的本地化字符串。
        /// </summary>
        internal static string SdkStartHttpPrefStuffNotNull {
            get {
                return ResourceManager.GetString("SdkStartHttpPrefStuffNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SDK订阅默认主题错误 的本地化字符串。
        /// </summary>
        internal static string SdkSubscribeDefaultTopicsError {
            get {
                return ResourceManager.GetString("SdkSubscribeDefaultTopicsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MQTT订阅主题错误 的本地化字符串。
        /// </summary>
        internal static string SdkSubscribeTopicError {
            get {
                return ResourceManager.GetString("SdkSubscribeTopicError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MQTT订阅主题成功 的本地化字符串。
        /// </summary>
        internal static string SdkSubscribeTopicSuccess {
            get {
                return ResourceManager.GetString("SdkSubscribeTopicSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MQTT取消订阅主题错误 的本地化字符串。
        /// </summary>
        internal static string SdkUnSubscribeTopicError {
            get {
                return ResourceManager.GetString("SdkUnSubscribeTopicError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MQTT取消订阅主题成功 的本地化字符串。
        /// </summary>
        internal static string SdkUnSubscribeTopicSuccess {
            get {
                return ResourceManager.GetString("SdkUnSubscribeTopicSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SDK更新讨论组信息错误 的本地化字符串。
        /// </summary>
        internal static string SdkUpdateGroupError {
            get {
                return ResourceManager.GetString("SdkUpdateGroupError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SDK用户修改公告状态为已读错误 的本地化字符串。
        /// </summary>
        internal static string SdkUpdateNotificationsStateError {
            get {
                return ResourceManager.GetString("SdkUpdateNotificationsStateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新小米、华为、魅族、信鸽的信息错误 的本地化字符串。
        /// </summary>
        internal static string SdkUpdatePushDeviceTokenError {
            get {
                return ResourceManager.GetString("SdkUpdatePushDeviceTokenError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SDK解散讨论组错误 的本地化字符串。
        /// </summary>
        internal static string SdkUpdateUserGroupConfigError {
            get {
                return ResourceManager.GetString("SdkUpdateUserGroupConfigError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SDK更新用户信息错误 的本地化字符串。
        /// </summary>
        internal static string SdkUpdateUserInfoError {
            get {
                return ResourceManager.GetString("SdkUpdateUserInfoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SDK更新聊天室信息错误 的本地化字符串。
        /// </summary>
        internal static string SdkUpdChartRommError {
            get {
                return ResourceManager.GetString("SdkUpdChartRommError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SDK更新聊天室成员属性错误 的本地化字符串。
        /// </summary>
        internal static string SdkUpdChartRommMemberError {
            get {
                return ResourceManager.GetString("SdkUpdChartRommMemberError", resourceCulture);
            }
        }
    }
}
